### ISSUE TITLE
请问如何在python程序中使用？

### ISSUE THREAD

**Issue by daishuge** [zhile-io/pandora#165]
我之前看作者之前的账号的一个议题：![Screenshot_2023-10-14-12-31-11-801_com.android.chrome-edit.jpg](https://github.com/zhile-io/pandora/assets/122254868/c07d2b6e-5456-4382-9466-03398d2705d1)

但是现在无法查看，我只有之前一个评论区大佬给的代码![Screenshot_2023-10-14-12-33-35-531_com.github.android.jpg](https://github.com/zhile-io/pandora/assets/122254868/cc987847-7c2b-4f6c-b629-fd5ead2ee90d)

https://github.com/daishuge/-fakegpt-with-history/blob/main/fake_api.py
请问如何申请这个key然后使用？

**Comment by undefinedcodezhong** [comment]
access token: https://ai.fakeopen.com/auth
share token: https://ai.fakeopen.com/token
pool token: https://ai.fakeopen.com/pool
先用账号密码获取access token，再去用access token生成share token，share token已经能当成api key用了，如果有多个账号，可以再生成pool token以实现并发使用（当然受到作者服务器限制也有限流）
另外这是一个获取pool token的自动化脚本：https://github.com/mufeng510/Free-ChatGPT-API
ps: 图里那个程序最早应该也是我发的哈哈

**Comment by daishuge** [comment]
感谢大佬!大佬牛逼!!!!

**Comment by undefinedcodezhong** [comment]
> pandora这个包不需要导入文件中执行吗

不需要哦，只需要通过作者网站拿到share token/pool token

**Comment by long202258** [comment]
那这个包得作用是什么？ 有具体得代码参考吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhile-io/pandora"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 晚上8:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhile-io/pandora] 请问如何在python程序中使用？ (Issue #165)





  
pandora这个包不需要导入文件中执行吗
  
不需要哦，只需要通过作者网站拿到share token/pool token

**Comment by daishuge** [comment]
> 那这个包得作用是什么？ 有具体得代码参考吗
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhile-io/pandora" ***@***.***&gt;; 发送时间:&nbsp;2023年10月23日(星期一) 晚上8:54 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [zhile-io/pandora] 请问如何在python程序中使用？ (Issue #165) pandora这个包不需要导入文件中执行吗 不需要哦，只需要通过作者网站拿到share token/pool token — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我有一些程序,请参考:
https://github.com/daishuge/-fakegpt-with-history : 一个使用ai.fakeopen.com的api的包含聊天概括功能的ai聊天机器人
https://github.com/daishuge/qqgpt_basic : 把chatgpt api的流式输出变为一句一句输出,适用于qq等聊天机器人

**Comment by long202258** [comment]
谢谢 这个两个代码我有在尝试，一直没有反应，生成不了内容不知道怎么回事




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhile-io/pandora"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月23日(星期一) 晚上8:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zhile-io/pandora] 请问如何在python程序中使用？ (Issue #165)





  
那这个包得作用是什么？ 有具体得代码参考吗
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhile-io/pandora" @.&gt;; 发送时间:&nbsp;2023年10月23日(星期一) 晚上8:54 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [zhile-io/pandora] 请问如何在python程序中使用？ (Issue #165) pandora这个包不需要导入文件中执行吗 不需要哦，只需要通过作者网站拿到share token/pool token — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
我有一些程序,请参考:
 https://github.com/daishuge/-fakegpt-with-history : 一个使用ai.fakeopen.com的api的包含聊天概括功能的ai聊天机器人
 https://github.com/daishuge/qqgpt_basic : 把chatgpt api的流式输出变为一句一句输出,适用于qq等聊天机器人

**Comment by daishuge** [comment]
> commented [Oct 23, 2023](#issuecomment-1775133032) via email

估计要么网络问题要么api问题,又或者是账号

**Comment by jiupinjiandingshi** [comment]
它好像还是收到ip 的频率限制 3/10s的那个

**Comment by jiupinjiandingshi** [comment]
它好像还是收到ip 的频率限制 3/10s的那个

**Comment by lys623** [comment]
> access token: https://ai.fakeopen.com/auth share token: https://ai.fakeopen.com/token pool token: https://ai.fakeopen.com/pool 先用账号密码获取access token，再去用access token生成share token，share token已经能当成api key用了，如果有多个账号，可以再生成pool token以实现并发使用（当然受到作者服务器限制也有限流） 另外这是一个获取pool token的自动化脚本：https://github.com/mufeng510/Free-ChatGPT-API ps: 图里那个程序最早应该也是我发的哈哈

大佬，请教下，有30个share token的话，只能支持30个并发吗？看文档说每个账号有一个会话的限制。 @undefinedcodezhong

**Comment by jiupinjiandingshi** [comment]
> > access token: https://ai.fakeopen.com/auth share token: https://ai.fakeopen.com/token pool token: https://ai.fakeopen.com/pool 先用账号密码获取access token，再去用access token生成share token，share token已经能当成api key用了，如果有多个账号，可以再生成pool token以实现并发使用（当然受到作者服务器限制也有限流） 另外这是一个获取pool token的自动化脚本：https://github.com/mufeng510/Free-ChatGPT-API ps: 图里那个程序最早应该也是我发的哈哈
> 
> 大佬，请教下，有30个share token的话，只能支持30个并发吗？看文档说每个账号有一个会话的限制，那挺容易429啊@undefinedcodezhong

同问 因为我现在不管多少个share token 聚合的Pool token 都只有三次的并发
