### ISSUE TITLE
今天3.5突然用不了，但是4可以用，不知道为什么

### ISSUE THREAD

**Issue by 7BlackJack** [zhile-io/pandora#250]
在3.5问 他就报错
our systems have detected unusual activity from your system.Please try again later

**Comment by xiaobaibai12** [comment]
同样问题 +1

**Comment by tobi0520** [comment]
同样的问题 + 1

**Comment by rodren-lion** [comment]
同样问题。。。 以为验证问题。。。退出后 登录不了。。。
![image](https://github.com/zhile-io/pandora/assets/60810175/c7a1ecd6-ff02-4bd0-b943-9e414ccdff42)

HTTPSConnectionPool(host='ai-20231023.fakeopen.com', port=443): Max retries exceeded with url: /auth/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f56286d87c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))




是不是GPT升级变动了。。

**Comment by onReadyL** [comment]
Serverless部署的项目也同样遇到这个问题

**Comment by RyanFarfetch** [comment]
![image](https://github.com/zhile-io/pandora/assets/37996775/c6a730b5-3bbb-49db-88c6-df3d60c3d503)
同样的问题

**Comment by xj1234567** [comment]
同样的问题+1

**Comment by tetabc** [comment]
+1 被制裁了吗

**Comment by ahlkddhfklh** [comment]
Our systems have detected unusual activity from your system. Please try again later.

**Comment by huozhiwei** [comment]
> Our systems have detected unusual activity from your system. Please try again later.

+1

**Comment by ishow520** [comment]
+1
